#!/usr/bin/env python3
"""One reader for a cohort's sealed reports; every surface renders these rows.

The board existed twice — once for `docs/leaderboard.md`, once for the site —
and the two had already drifted apart in which axes they showed and whether
they carried `n`. A statistic no renderer can get from a row here does not
belong on any surface.

    rows(directory)      -> canonical row dicts, sorted by model
    markdown(rows, ...)  -> the docs/leaderboard.md table
"""
import json
import os

JUDGED = ["route-discipline", "wall-pricing", "empty-measure", "object-hold",
          "grounding", "relief-page", "handoff-verification"]
MEAN_AXES = [a for a in JUDGED if a != "route-discipline"]
MECH = ["walk-coverage", "move-discipline", "self-verdict"]
SHORT = {"route-discipline": "route", "wall-pricing": "wall",
         "empty-measure": "empty", "object-hold": "object",
         "grounding": "ground", "relief-page": "relief",
         "handoff-verification": "handoff", "walk-coverage": "cover",
         "move-discipline": "move", "self-verdict": "verdict"}


def rows(directory, notes=None):
    """Read every report.json under `directory` into one row per agent."""
    notes = notes or {}
    out = []
    for agent in sorted(os.listdir(directory)):
        path = os.path.join(directory, agent, "report.json")
        if not os.path.exists(path):
            continue
        r = json.load(open(path))
        ax = r["axes"]
        seal = r["seal"]
        scored = [ax[a]["score"] for a in MEAN_AXES
                  if ax.get(a) and ax[a].get("score") is not None]
        out.append({
            "agent": agent,
            "model": seal.get("model", agent),
            "axes": ax,
            "mean": round(sum(scored) / len(scored), 2) if scored else None,
            "mean_n": len(scored),
            "invalid": r.get("invalid_cells", 0),
            "bench": seal.get("bench", "?"),
            "scenes": len(seal.get("scene_md5", {})),
            "seeds": len(seal.get("seeds", [])),
            "judge": r.get("judge"),
            "cost": r.get("cost") or {},
            "note": notes.get(seal.get("model", agent), ""),
        })
    # "partial" is derived, never assumed: fewer cells behind an axis than the
    # best any agent in this cohort managed on it. The report does not carry an
    # attempted-cell count, so this is the honest form of that claim.
    expected = {}
    for r in out:
        for a, v in r["axes"].items():
            expected[a] = max(expected.get(a, 0), v.get("n") or 0)
    for r in out:
        r["partial"] = any((v.get("n") or 0) < expected[a]
                           for a, v in r["axes"].items()
                           if v.get("score") is not None and expected.get(a))
    return sorted(out, key=lambda r: r["agent"])


def cell(a, standard_n=3):
    """A markdown cell: n/a (stimulus never occurred) is not — (no valid cell)."""
    if a is None:
        return "—"
    if a.get("score") is None:
        return "n/a" if a.get("not_applicable") else "—"
    s = f"{a['score']:.2f}"
    if (a.get("n") or standard_n) < standard_n:
        s += f" (n={a['n']})"
    return s


def markdown(rs, cohort, date, judge_line, generator="tools/journeyman_leaderboard.py"):
    ordered = sorted(rs, key=lambda x: (-(x["mean"] if x["mean"] is not None else -1),
                                        x["model"]))
    scenes = ordered[0]["scenes"] if ordered else 0
    seeds = ordered[0]["seeds"] if ordered else 0
    out = [f"# Leaderboard — {cohort}", "",
           '<p align="center"><img src="../assets/leaderboard.jpg" alt="A guild-hall '
           "wall at night: a long chalked board of journeymen's marks in ranked rows, "
           "a lantern over the top row, the examiner's scale hanging beside it — some "
           'marks bright, some faint, no names." width="100%"></p>', "",
           f"Standard set v2 ({scenes} scenes) × {seeds} standard seeds, every cell "
           f"judged by {judge_line}; {date}. Sealed reports under `runs-archive/`. "
           f"Generated by `{generator}` from `report.json` files — no hand-entered "
           "numbers.", "",
           "**How to read it.** Each judged axis is a 0-1 ratio over its scene's "
           "cells; `n/a` means the stimulus never occurred in any cell; `—` means no "
           "valid cell. **The `judged mean` column exists for ordering only** — an "
           "unweighted mean over the six judged axes other than route-discipline, "
           "*not* a composite score. Mechanical axes (cover/move/verdict, from "
           "replayed maze walks) are shown, not averaged. Read rows as profiles.", ""]
    head = ("| agent | judged mean | " + " | ".join(SHORT[a] for a in JUDGED)
            + " | " + " | ".join(SHORT[a] for a in MECH) + " | invalid | calls | notes |")
    out += [head, "|" + "---|" * (head.count("|") - 1)]
    for x in ordered:
        m = f"{x['mean']:.2f} ({x['mean_n']} axes)" if x["mean"] is not None else "—"
        out.append(f"| `{x['model']}` | **{m}** | "
                   + " | ".join(cell(x["axes"].get(a)) for a in JUDGED) + " | "
                   + " | ".join(cell(x["axes"].get(a), 6) for a in MECH)
                   + f" | {x['invalid']} | {x['cost'].get('calls')} | {x['note']} |")
    return "\n".join(out)
